import streamlit as st
import pandas as pd
import joblib

st.set_page_config(
    page_title="Ames House Price Predictor",
    page_icon="🏠",
    layout="wide"
)

MODEL_PATH = "models/04_ridge.joblib"

st.title("🏠 Ames House Price Predictor")
st.write(
    "An interactive house-price prediction app built as part of my "
    "Regression Models training at the Arab Academy."
)

st.info(
    "The prediction is generated by the trained Ridge Regression pipeline "
    "from the regression models notebook."
)

st.header("Enter House Information")

col1, col2, col3 = st.columns(3)

with col1:
    gr_liv_area = st.number_input("Living Area (sq ft)", min_value=300, max_value=6000, value=1800, step=50)
    total_bsmt_sf = st.number_input("Total Basement Area (sq ft)", min_value=0, max_value=5000, value=900, step=50)
    first_flr_sf = st.number_input("1st Floor Area (sq ft)", min_value=300, max_value=5000, value=1000, step=50)
    lot_area = st.number_input("Lot Area (sq ft)", min_value=1000, max_value=100000, value=9000, step=500)
    overall_qual = st.slider("Overall Quality", 1, 10, 7)
    overall_cond = st.slider("Overall Condition", 1, 10, 5)
    year_built = st.number_input("Year Built", min_value=1800, max_value=2026, value=2001, step=1)
    year_remod = st.number_input("Year Remodeled", min_value=1800, max_value=2026, value=2001, step=1)
    garage_cars = st.number_input("Garage Capacity (cars)", min_value=0, max_value=6, value=2, step=1)

with col2:
    garage_area = st.number_input("Garage Area (sq ft)", min_value=0, max_value=2000, value=500, step=50)
    full_bath = st.number_input("Full Bathrooms", min_value=0, max_value=5, value=2, step=1)
    half_bath = st.number_input("Half Bathrooms", min_value=0, max_value=3, value=1, step=1)
    tot_rms = st.number_input("Rooms Above Ground", min_value=1, max_value=20, value=7, step=1)
    fireplaces = st.number_input("Fireplaces", min_value=0, max_value=5, value=1, step=1)
    mas_vnr_area = st.number_input("Masonry Veneer Area (sq ft)", min_value=0, max_value=2000, value=120, step=20)
    wood_deck_sf = st.number_input("Wood Deck Area (sq ft)", min_value=0, max_value=1500, value=150, step=25)
    open_porch_sf = st.number_input("Open Porch Area (sq ft)", min_value=0, max_value=1000, value=40, step=10)

with col3:
    neighborhood = st.selectbox(
        "Neighborhood",
        ["Blmngtn", "Blueste", "BrDale", "BrkSide", "ClearCr", "CollgCr",
         "Crawfor", "Edwards", "Gilbert", "Greens", "GrnHill", "IDOTRR",
         "Landmrk", "MeadowV", "Mitchel", "NAmes", "NoRidge", "NPkVill",
         "NridgHt", "NWAmes", "OldTown", "Sawyer", "SawyerW", "Somerst",
         "StoneBr", "SWISU", "Timber", "Veenker"],
        index=5
    )
    house_style = st.selectbox(
        "House Style",
        ["1.5Fin", "1.5Unf", "1Story", "2.5Fin", "2.5Unf", "2Story", "SFoyer", "SLvl"],
        index=5
    )
    bldg_type = st.selectbox("Building Type", ["1Fam", "2fmCon", "Duplex", "Twnhs", "TwnhsE"], index=0)
    exter_qual = st.selectbox("Exterior Quality", ["Ex", "Gd", "TA", "Fa"], index=1)
    kitchen_qual = st.selectbox("Kitchen Quality", ["Ex", "Gd", "TA", "Fa"], index=1)
    bsmt_qual = st.selectbox("Basement Quality", ["Ex", "Gd", "TA", "Fa", "Missing"], index=1)
    heating_qc = st.selectbox("Heating Quality", ["Ex", "Gd", "TA", "Fa", "Po"], index=0)
    central_air = st.selectbox("Central Air", ["Y", "N"], index=0)
    foundation = st.selectbox("Foundation", ["BrkTil", "CBlock", "PConc", "Slab", "Stone", "Wood"], index=2)
    garage_type = st.selectbox(
        "Garage Type",
        ["2Types", "Attchd", "Basment", "BuiltIn", "CarPort", "Detchd", "Missing"],
        index=1
    )

if st.button("🔮 Predict House Price", type="primary", use_container_width=True):
    try:
        model = joblib.load(MODEL_PATH)

        new_house = pd.DataFrame([{
            "Gr Liv Area": gr_liv_area,
            "Total Bsmt SF": total_bsmt_sf,
            "1st Flr SF": first_flr_sf,
            "Lot Area": lot_area,
            "Overall Qual": overall_qual,
            "Overall Cond": overall_cond,
            "Year Built": year_built,
            "Year Remod/Add": year_remod,
            "Garage Cars": garage_cars,
            "Garage Area": garage_area,
            "Full Bath": full_bath,
            "Half Bath": half_bath,
            "TotRms AbvGrd": tot_rms,
            "Fireplaces": fireplaces,
            "Mas Vnr Area": mas_vnr_area,
            "Wood Deck SF": wood_deck_sf,
            "Open Porch SF": open_porch_sf,
            "Neighborhood": neighborhood,
            "House Style": house_style,
            "Bldg Type": bldg_type,
            "Exter Qual": exter_qual,
            "Kitchen Qual": kitchen_qual,
            "Bsmt Qual": bsmt_qual,
            "Heating QC": heating_qc,
            "Central Air": central_air,
            "Foundation": foundation,
            "Garage Type": garage_type,
        }])

        prediction = model.predict(new_house)[0]

        st.success(f"### Estimated Sale Price: ${prediction:,.0f}")
        st.caption(
            "This is an educational prediction based on the trained model and "
            "should not be treated as a professional property valuation."
        )

    except FileNotFoundError:
        st.error(
            f"Model file not found: {MODEL_PATH}. "
            "Make sure the models folder is uploaded to the repository."
        )
    except Exception as e:
        st.error(f"Prediction error: {e}")